config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root to: "pages#home"

  match '/signup',  to: "users#new"
  match '/signin',  to: "sessions#new"
  match '/signout', to: "sessions#destroy"
  match '/contact', to: "pages#contact"
  match '/help',    to: "pages#help"
  match '/about',   to: "pages#about"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { maximum: 50 }, presence: true
  validates :email, format: { with: email_regex }, uniqueness: { case_sensitive: false},  presence: true
  validates :password, confirmation: true, length: { within: 6..40 }, presence: true

  before_save :encrypt_password

  def self.authenticate(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user :nil
  end

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def make_salt
    secure_hash("#{Time.now.utc}")
    #secure_hash("#{Time.now.utc}--#{password}")
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'Home'
  end

  def contact
    @title = 'Contact'
  end

  def help
    @title = 'Help'
  end

  def about
    @title = 'About'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = 'Sign in'
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = 'Invalid email/password combination'
      @title = 'Sign in'
      render 'new'
    else
      sign_in(user)
      redirect_to(user)
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = 'Sign up'
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      flash[:success] = 'Welcome to the sample app!'
      redirect_to @user
    else
      @title = 'Sign up'
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_url = 'Ruby on Rails Tutorial | '
    if @title.nil?
      return base_url
    else
      return base_url + @title
    end
  end

  def active_item_menu(page)
    'active' if current_page?(page)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 } )
    gravatar_image_tag(user.email.downcase, alt: @user.name,
                                            class: 'gravatar',
                                            gravatar: options)
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Sample app 2013</p>
</div>

app/views/layouts/_header.html.erb
<div class="masthead">
  <ul class="nav nav-pills pull-right">
    <li class="<%= active_item_menu(root_path) %>"><%= link_to 'Home', root_path %></li>
    <li class="<%= active_item_menu(contact_path) %>"><%= link_to 'Contact', contact_path %></li>
    <li class="<%= active_item_menu(help_path) %>"><%= link_to 'Help', help_path %></li>
    <li class="<%= active_item_menu(about_path) %>"><%= link_to 'About', about_path %></li>
    <% if signed_in? %>
      <li class="<%= active_item_menu(signout_path) %>"><%= link_to 'Sign out', signout_path, method: :delete %></li>
    <% else %>
      <li class="<%= active_item_menu(signin_path) %>"><%= link_to 'Sign in', signin_path %></li>
    <% end %>
  </ul>
  <h3 class="muted">Sample application</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-narrow">

  <%= render 'layouts/header' %>
    <div>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

  <hr>

  <div class="jumbotron">
    <%= yield %>
  </div>

  <hr>

  <%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/pages/about.html.erb
<h3>About Us</h3>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h3>Contact</h3>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/help.html.erb
<h3>Help</h3>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h3>Sample App</h3>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

<div class="signupbtn">
  <%= link_to 'Sign up now!', signup_path, class: 'btn btn-large btn-success' %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation" class="alert">
      <h5><%= pluralize(@user.errors.count, 'error') %>
        prohibited this user from being saved:</h5>
      <p>There were problems with following fields:</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<h3>New user</h3>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <div>
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>

  <div>
    <%= f.text_field :email, placeholder: 'Email' %>
  </div>

  <div>
    <%= f.password_field :password, placeholder: 'Password' %>
  </div>
  <div>
    <%= f.password_field :password_confirmation, placeholder: 'Password confirmation' %>
  </div>
  <div>
    <%= f.button 'Sign up', class: 'btn-danger' %>
  </div>
<% end %>

app/views/users/show.html.erb
<h3>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h3>